const ACTION_TYPES = {
  CHANGE_INPUT: "CHANGE_INPUT",
  FETCH_URLS_SUCCESS: "FETCH_URLS_SUCCESS",
  FETCH_VISITS_SUCCESS: "FETCH_VISITS_SUCCESS",
  FETCH_START: "FETCH_START",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
  POST_START: "POST_START",
  POST_SUCCESS: "POST_SUCCESS",
  POST_ERROR: "POST_ERROR",
  SHRINK_URL_START: "SHRINK_URL_START",
  SHRINK_URL_SUCCESS: "SHRINK_URL_SUCCESS",
  SHRINK_URL_ERROR: "SHRINK_URL_ERROR",
};

export default ACTION_TYPES;
