const ACTION_TYPES = {
  CHANGE_INPUT: "CHANGE_INPUT",
  FETCH_START: "FETCH_START",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
  POST_START: "POST_START",
  POST_SUCCESS: "POST_SUCCESS",
  POST_ERROR: "POST_ERROR",
};

export default ACTION_TYPES;
